# Welcome to Jekyll!

# Site settings
title: 相爱·相知·相许
description: |
  <h3>帅哥 <strong>♡</strong> 美女</h3>
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  我想和你在初春相遇，<br />
  撑把油纸伞，陪你徜徉在悠长的雨巷，<br />
  而你美丽的额头开满了丁香。
owner: uraplutonium
first_published: 2016
email: uraplutonium@yandex.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uraplutonium.github.io" # the base hostname & protocol for your site
social:

  
# Build settings
markdown: kramdown
#sass:
#  style: compressed
