# Welcome to Jekyll!

# Site settings
title: 相爱·相知·相许
description: |
  <h3>丁飞 <strong>♡</strong> 贺煜星</h3>
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  你是一朵红红的玫瑰，<br />
  美到让我心醉。
owner: uraplutonium
first_published: 2016
email: uraplutonium@yandex.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uraplutonium.github.io" # the base hostname & protocol for your site
social:
  email: http://uraplutonium@yandex.com
  linkedin-square: https://linkedin.com/in/飞-丁-26273b32
  github: https://github.com/uraplutonium
  facebook-official: https://facebook.com/uraplutonium
  
# Build settings
markdown: kramdown
#sass:
#  style: compressed
