# Welcome to Jekyll!
#

# Site settings
title: 标题
description: |
  描述，描述，很长很长的描述
  这个描述换行了，但还未结束
  甚至还有个超链接：请戳[百度](http://www.baidu.com)
owner: uraplutonium
first_published: 2016
email: uraplutonium@yandex.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uraplutonium.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/Felix__Ting
  github: https://github.com/uraplutonium
  linkedin-square: https://linkedin.com/in/飞-丁-26273b32
  facebook-official: https://facebook.com/uraplutonium
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: uraplutonium@yandex.com
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
